student_list=['rahul','karan','mohan','pooja','sam','kamal','trivedi','nandani','shiv','singh']
print(student_list, 'student_list normal')
student_list.append('avni')
print(student_list,'student list after append call')
student_list.remove('rahul')
print(student_list,'student list after remove call')
student_list.pop(3)
print(student_list,'student list after pop call')
student_list=list('vinay')
print(student_list,'student list after list() call')
